### ISSUE TITLE
[BE] AWS이용해 배포하기 

### ISSUE THREAD

**Issue by bohyeon-n** [codesquad-member-2020/todo-8#23]
**필수**
- [ ]  aws ec2 인스턴스 생성 
- [ ] 백엔드 배포 (gradlew build로 jar를 생성하고 이를 이용해서 실행)
- [ ] 프론트 배포 (Nginx)
- [ ]  local 프로젝트와 배포된 mysql 인스턴스를 연결해본다

**선택** 
- [ ] 80포트 하나로 동작하도록 하고, proxy 설정을 통해 api요청은 8080으로 넘긴다
- [ ] ec2 서버의 80포트만 외부에 공개한다

**Comment by 102092** [comment]
#### 필수
 - [x] aws ec2 인스턴스 생성
 - [x] 백엔드 배포 (gradlew build로 jar를 생성하고 이를 이용해서 실행)
-  [x] 프론트 배포 (Nginx)
 - [x] local 프로젝트와 배포된 mysql 인스턴스를 연결해본다
#### 선택
- [x] 80포트 하나로 동작하도록 하고, proxy 설정을 통해 api요청은 8080으로 넘긴다
- [x]  ec2 서버의 80포트만 외부에 공개한다

#### 배포
- [http://34.236.252.205](http://34.236.252.205/)
- [http://34.236.252.205/api/](http://34.236.252.205/api/)

**Comment by bohyeon-n** [comment]
**필수**
- [X]  aws ec2 인스턴스 생성 
- [X] 백엔드 배포 (gradlew build로 jar를 생성하고 이를 이용해서 실행)
- [X] 프론트 배포 (Nginx) => 실제 프론트 소스 코드가 아니라, index.html을 생성해서 테스트만 함 
- [ ]  local 프로젝트와 배포된 mysql 인스턴스를 연결해본다

**선택** 
- [X] 80포트 하나로 동작하도록 하고, proxy 설정을 통해 api요청은 8080으로 넘긴다
- [X] ec2 서버의 80포트만 외부에 공개한다

배포 
- [http://13.125.160.249/](http://13.125.160.249/)
- [http://13.125.160.249/api](http://13.125.160.249/api)
